spring:
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

  data:
    mongodb:
      database: springBatch
      uri: mongodb://localhost
      port: 27017

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    job:
      enabled: false

