spring:
  liquibase.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#  jpa:
#    show-sql: true
logging:
  level:
    sql: info