
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/asdf;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:h2memdb
    username: sys
    password: sys
  h2:
    console:
      enabled: true
      path: /h2-console
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=acl
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
    enabled: true
