spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      schema: acl
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
    enabled: true
#logging:
#  level:
#    liquibase: trace
#    org:
#      hibernate: info

