spring:
  data:
    mongodb:
      database: library
      uri: mongodb://localhost
      port: 27017
#      username: admin
#      password: password

logging.level.org.hibernate: info
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: info



